In [1]:
import numpy as np

In [13]:
n = 10
x = np.array(range(n - 1, 0, -1))
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [16]:
n = 10
x = np.diag(np.array(range(n - 1, 0, -1)))
x

array([[9, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [11]:
sum(range(n))

45

In [18]:
# 4x + 2y +  z = 4
#  x + 3y      = 12
#      5y + 4z = -3
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
x = np.linalg.solve(a, b)
x

array([ 0.46666667,  3.84444444, -5.55555556])

In [19]:
4 * 0.46666667 + 2 * 3.84444444 +  -5.55555556

4.0